name: Build & Deploy API

on: 
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
  
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    deploy:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: write

      needs: build

      steps:
        - name: Checkout code
          uses: actions/checkout@v2  
        - name: Deploy docker-compose
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.SERVER_ADRESS }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            source: "docker-compose.yml"
            target: "/home/ratiscrum/ratigreen"
        - name: Deploy API
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_ADRESS }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              cd ratigreen/
              docker-compose -f docker-compose.yml pull
              docker-compose -f docker-compose.yml down
              docker-compose -f docker-compose.yml --env-file ./.env up -d ratigreen-api